"""Protein shakes built on whey, casein, collagen, dairy and eggs."""

RECIPES = [
    # ------------------------------------------------ post-lift recovery
    ("pr1-second-wind", "Second Set", "protein", 1, 3, [
        ("milk_skim", 0.75, "cup"),
        ("banana_frozen", 0.5, "cup"),
        ("whey_chocolate", 1, "piece"),
        ("oats", 0.25, "cup"),
        ("peanut_powder", 3, "tbsp"),
        ("honey", 1, "tbsp"),
    ], "Raw oats blend smoother if you soak them in the milk for five minutes first."),
    ("pr1-the-refill", "The Refill", "protein", 1, 4, [
        ("oat_milk", 0.75, "cup"),
        ("mango_frozen", 0.5, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("oats", 0.25, "cup"),
        ("date", 2, "piece"),
    ], "Pit the dates and tear them in half — whole ones ride on top of the blade."),
    ("pr1-cooldown-cherry", "Cooldown Cherry", "protein", 1, 3, [
        ("cherry_juice", 0.5, "cup"),
        ("cherry_frozen", 0.5, "cup"),
        ("greek_yogurt_nonfat", 0.25, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("oats", 0.25, "cup"),
        ("honey", 1, "tbsp"),
    ], "Unflavored whey lets the cherry stay tart; vanilla whey would flatten it out."),
    ("pr1-finisher-mocha", "Finisher Mocha", "protein", 1, 3, [
        ("cold_brew", 0.25, "cup"),
        ("milk_whole", 0.5, "cup"),
        ("banana_frozen", 0.5, "cup"),
        ("whey_chocolate", 1, "piece"),
        ("oats", 0.5, "cup"),
        ("salt", 0.25, "tsp"),
    ], "The salt is not optional — it is what makes the chocolate read as chocolate."),
    ("pr1-rebuild-mango", "Rebuild Mango", "protein", 1, 3, [
        ("milk_whole", 0.5, "cup"),
        ("mango_frozen", 0.5, "cup"),
        ("greek_yogurt_whole", 0.25, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("oats", 0.25, "cup"),
        ("honey", 1, "tbsp"),
    ], "Frozen mango beats fresh here — fresh mango thins the yogurt out within the minute."),
    ("pr1-heavy-set-chocolate", "Heavy Set Chocolate", "protein", 1, 3, [
        ("milk_2", 0.75, "cup"),
        ("banana_frozen", 0.5, "cup"),
        ("whey_chocolate", 1, "piece"),
        ("cacao_powder", 1, "tbsp"),
        ("almond_butter", 1, "tbsp"),
        ("maple_syrup", 1, "tbsp"),
    ], "Cacao powder on top of chocolate whey is what turns it from sweet to dark."),
    ("pr1-pineapple-reload", "Pineapple Reload", "protein", 1, 3, [
        ("pineapple_juice", 0.5, "cup"),
        ("pineapple_frozen", 0.5, "cup"),
        ("greek_yogurt_nonfat", 0.5, "cup"),
        ("whey_isolate", 1, "piece"),
        ("electrolyte_powder", 1, "tsp"),
    ], "Fresh pineapple will thin dairy out over an hour, so drink this one straight away."),
    ("pr1-honeycomb-oats", "Honeycomb Oats", "protein", 1, 4, [
        ("milk_skim", 0.75, "cup"),
        ("banana", 0.5, "piece"),
        ("whey_vanilla", 1, "piece"),
        ("oats", 0.25, "cup"),
        ("honey", 1.5, "tbsp"),
        ("cinnamon", 0.5, "tsp"),
    ], "Use a banana with brown freckles; a green one tastes starchy against the honey."),

    # ------------------------------------------------ lean, under 250 kcal
    ("pr1-featherweight-vanilla", "Featherweight Vanilla", "protein", 1, 2, [
        ("almond_milk", 1, "cup"),
        ("ice", 0.75, "cup"),
        ("whey_isolate", 1, "piece"),
        ("vanilla_extract", 0.5, "tsp"),
        ("stevia", 0.25, "tsp"),
    ], "Isolate foams badly if you run it long — thirty seconds on BLEND is plenty."),
    ("pr1-snow-day-strawberry", "Snow Day Strawberry", "protein", 1, 2, [
        ("water", 0.5, "cup"),
        ("strawberry_frozen", 0.75, "cup"),
        ("greek_yogurt_nonfat", 0.25, "cup"),
        ("whey_strawberry", 1, "piece"),
        ("lemon_zest", 0.5, "tsp"),
    ], "Zest, not juice — the oil in the peel carries strawberry further than acid does."),
    ("pr1-raspberry-frost", "Raspberry Frost", "protein", 1, 2, [
        ("almond_milk", 0.75, "cup"),
        ("raspberry_frozen", 0.75, "cup"),
        ("whey_isolate", 1, "piece"),
        ("xanthan", 0.25, "tsp"),
    ], "A quarter teaspoon of xanthan is the whole trick: more and it turns to slime."),
    ("pr1-quiet-peach", "Quiet Peach", "protein", 1, 3, [
        ("almond_milk", 0.5, "cup"),
        ("peach_frozen", 0.75, "cup"),
        ("skyr", 0.25, "cup"),
        ("egg_protein", 1, "piece"),
        ("ginger_ground", 0.25, "tsp"),
    ], "Ground ginger, not fresh — fresh ginger fights the peach instead of backing it."),
    ("pr1-blue-hour", "Blue Hour", "protein", 1, 2, [
        ("almond_milk", 0.75, "cup"),
        ("blueberry_frozen", 0.5, "cup"),
        ("skyr", 0.25, "cup"),
        ("whey_isolate", 1, "piece"),
        ("lemon_juice", 1, "tsp"),
    ], "Skyr is stiffer than Greek yogurt, so pour the milk in first or it bridges the blade."),
    ("pr1-lime-cloud", "Lime Cloud", "protein", 1, 3, [
        ("greek_yogurt_nonfat", 0.5, "cup"),
        ("ice", 0.75, "cup"),
        ("water", 0.25, "cup"),
        ("whey_isolate", 1, "piece"),
        ("lime_juice", 2, "tbsp"),
        ("lime_zest", 0.5, "tsp"),
    ], None),
    ("pr1-cold-start-cocoa", "Cold Start Cocoa", "protein", 1, 2, [
        ("almond_milk", 1, "cup"),
        ("ice", 0.75, "cup"),
        ("whey_chocolate", 1, "piece"),
        ("cacao_powder", 1, "tbsp"),
        ("stevia", 0.25, "tsp"),
    ], None),
    ("pr1-clean-slate", "Blank Page", "protein", 1, 3, [
        ("egg_white", 0.75, "cup"),
        ("water", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("collagen", 1, "piece"),
        ("orange", 1, "piece"),
    ], "Buy pasteurized whites in a carton — this is not the place for a raw egg."),

    # ------------------------------------------------ casein, thick and slow
    ("pr1-lights-out-vanilla", "Lights Out Vanilla", "protein", 1, 3, [
        ("milk_2", 0.75, "cup"),
        ("ice", 0.5, "cup"),
        ("casein", 1, "piece"),
        ("almond_butter", 1, "tbsp"),
        ("cinnamon", 0.5, "tsp"),
    ], "Casein thickens for about a minute after it stops, so blend it looser than you want it."),
    ("pr1-deep-cocoa", "Deep Cocoa", "protein", 1, 3, [
        ("milk_skim", 0.75, "cup"),
        ("casein", 1, "piece"),
        ("cacao_powder", 1, "tbsp"),
        ("chia", 1, "tbsp"),
        ("date", 1, "piece"),
    ], "Add the chia at the end and give it two minutes, or it clumps against the blade."),
    ("pr1-ten-oclock-pudding", "Ten O'Clock Pudding", "protein", 1, 3, [
        ("milk_whole", 0.5, "cup"),
        ("greek_yogurt_whole", 0.5, "cup"),
        ("casein", 1, "piece"),
        ("chia", 1, "tbsp"),
        ("vanilla_bean", 0.5, "tsp"),
    ], "Leave it in the fridge twenty minutes and it sets thick enough to eat with a spoon."),
    ("pr1-night-shift-cherry", "Night Shift Cherry", "protein", 1, 3, [
        ("chamomile_tea", 0.5, "cup"),
        ("cherry_juice", 0.25, "cup"),
        ("cherry_frozen", 0.5, "cup"),
        ("casein", 1, "piece"),
        ("skyr", 0.25, "cup"),
    ], "Brew the chamomile double strength and chill it, or the cherry buries it completely."),
    ("pr1-slow-roll-peanut", "Slow Roll Peanut", "protein", 1, 3, [
        ("milk_2", 0.75, "cup"),
        ("banana", 0.5, "piece"),
        ("casein", 1, "piece"),
        ("peanut_butter", 1, "tbsp"),
        ("salt", 0.25, "tsp"),
    ], None),
    ("pr1-cassis-nightcap", "Cassis Nightcap", "protein", 1, 4, [
        ("milk_skim", 0.5, "cup"),
        ("quark", 0.5, "cup"),
        ("blackcurrant", 0.25, "cup"),
        ("casein", 1, "piece"),
        ("honey", 1, "tsp"),
    ], "Black currants are sharper than blackberries — taste before you add a second spoon of honey."),

    # ------------------------------------------------ collagen and coffee
    ("pr1-desk-drawer-cold-brew", "Desk Drawer Cold Brew", "protein", 1, 2, [
        ("cold_brew", 0.5, "cup"),
        ("milk_skim", 0.75, "cup"),
        ("ice", 0.5, "cup"),
        ("collagen", 1, "piece"),
        ("whey_unflavored", 1, "piece"),
    ], "Collagen dissolves in cold liquid without foaming, so it goes in before the ice."),
    ("pr1-morning-pour", "Morning Pour", "protein", 1, 3, [
        ("oat_milk_barista", 0.75, "cup"),
        ("skyr", 0.5, "cup"),
        ("espresso", 2, "piece"),
        ("collagen", 1, "piece"),
        ("cinnamon", 0.5, "tsp"),
    ], "Pull the espresso over ice first — hot coffee poured onto skyr will split it."),
    ("pr1-istanbul-morning", "Istanbul Morning", "protein", 1, 3, [
        ("coffee", 0.5, "cup"),
        ("milk_whole", 0.5, "cup"),
        ("greek_yogurt_nonfat", 0.25, "cup"),
        ("collagen", 1, "piece"),
        ("date", 1, "piece"),
        ("cardamom", 0.25, "tsp"),
    ], "Cardamom in the coffee is the Turkish habit; a quarter teaspoon is already loud."),
    ("pr1-slow-drip-vanilla", "Slow Drip Vanilla", "protein", 1, 2, [
        ("cold_brew", 0.5, "cup"),
        ("skyr", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("collagen", 1, "piece"),
        ("maple_syrup", 1, "tsp"),
        ("vanilla_extract", 0.5, "tsp"),
    ], None),
    ("pr1-salted-honey-espresso", "Salted Honey Espresso", "protein", 1, 3, [
        ("milk_2", 0.75, "cup"),
        ("espresso", 2, "piece"),
        ("cottage_cheese", 0.25, "cup"),
        ("collagen", 1, "piece"),
        ("honey", 1, "tsp"),
        ("salt", 0.25, "tsp"),
    ], "Blend the cottage cheese with the milk alone for ten seconds first so no curds survive."),

    # ------------------------------------------------ dessert flavours, real macros
    ("pr1-crumb-and-cream", "Crumb and Cream", "protein", 1, 3, [
        ("milk_skim", 0.5, "cup"),
        ("cottage_cheese", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("whey_cookies", 1, "piece"),
        ("choc_cookie", 1, "piece"),
    ], "Save half the cookie and crush it on top — blending it all in just makes grey shake."),
    ("pr1-buckeye-shake", "Buckeye Shake", "protein", 1, 3, [
        ("milk_skim", 0.75, "cup"),
        ("banana_frozen", 0.5, "cup"),
        ("whey_chocolate", 1, "piece"),
        ("peanut_powder", 3, "tbsp"),
        ("choc_chips", 1, "tsp"),
    ], "Powdered peanut butter carries the flavour at a fifth of the fat of the real jar."),
    ("pr1-sunday-morning-swirl", "Sunday Morning Swirl", "protein", 1, 3, [
        ("milk_2", 0.5, "cup"),
        ("quark", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("cinnamon", 1, "tsp"),
        ("maple_syrup", 1, "tbsp"),
    ], "Quark is the sour-cream tang that makes this taste of frosting rather than of cinnamon toast."),
    ("pr1-confetti-shake", "Confetti Shake", "protein", 1, 2, [
        ("milk_skim", 0.75, "cup"),
        ("greek_yogurt_nonfat", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("almond_extract", 0.25, "tsp"),
        ("sprinkles", 1, "tsp"),
    ], "Almond extract is the whole birthday-cake illusion — vanilla alone never gets there."),
    ("pr1-venetian-nightcap", "Venetian Nightcap", "protein", 1, 4, [
        ("milk_skim", 0.75, "cup"),
        ("mascarpone", 2, "tbsp"),
        ("espresso", 2, "piece"),
        ("casein", 1, "piece"),
        ("cacao_powder", 1, "tsp"),
    ], "Two tablespoons of mascarpone is enough for the whole cup to taste rich; four turns it greasy."),
    ("pr1-porch-light-banana", "Porch Light Banana", "protein", 1, 3, [
        ("milk_skim", 0.5, "cup"),
        ("banana_frozen", 0.5, "cup"),
        ("greek_yogurt_nonfat", 0.25, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("vanilla_wafer", 3, "piece"),
        ("nutmeg", 0.25, "tsp"),
    ], "Grate the nutmeg over the top at the end; blended in, it just tastes dusty."),
    ("pr1-burnt-sugar-and-salt", "Burnt Sugar and Salt", "protein", 1, 3, [
        ("milk_2", 0.5, "cup"),
        ("skyr", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("caramel_sauce", 1, "tbsp"),
        ("salt", 0.25, "tsp"),
    ], "Salt the caramel in the cup before blending so it dissolves instead of sitting in grains."),
    ("pr1-after-dinner-mint", "After Dinner Mint", "protein", 1, 3, [
        ("milk_skim", 0.75, "cup"),
        ("greek_yogurt_nonfat", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("peppermint_extract", 0.25, "tsp"),
        ("cacao_nibs", 1, "tbsp"),
    ], "Nibs stay crunchy where chocolate chips melt into streaks — pulse them in at the end."),
    ("pr1-strawberry-crust", "Strawberry Crust", "protein", 1, 3, [
        ("milk_skim", 0.5, "cup"),
        ("cottage_cheese", 0.5, "cup"),
        ("strawberry_frozen", 0.5, "cup"),
        ("whey_strawberry", 1, "piece"),
        ("graham_cracker", 1, "piece"),
        ("lemon_zest", 0.5, "tsp"),
    ], "Cottage cheese is what gives the cheesecake tang; blend it until you cannot see a single curd."),
    ("pr1-fudge-pop", "Fudge Pop", "protein", 1, 3, [
        ("milk_skim", 0.75, "cup"),
        ("avocado", 0.25, "piece"),
        ("ice", 0.5, "cup"),
        ("casein", 1, "piece"),
        ("cacao_powder", 1, "tbsp"),
        ("allulose", 1, "tbsp"),
    ], "A quarter of an avocado reads as fudge, not as avocado, as long as the cacao is unsweetened."),

    # ------------------------------------------------ fruit-forward and savoury-adjacent
    ("pr1-orchard-skyr", "Orchard Skyr", "protein", 1, 4, [
        ("kefir", 0.5, "cup"),
        ("apple_green", 0.5, "piece"),
        ("skyr", 0.25, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("cinnamon", 0.5, "tsp"),
    ], "Leave the apple skin on — it is where the tartness lives, and the Blast handles it."),
    ("pr1-yellow-flag", "Yellow Flag", "protein", 1, 3, [
        ("passionfruit_juice", 0.5, "cup"),
        ("mango_frozen", 0.5, "cup"),
        ("greek_yogurt_nonfat", 0.5, "cup"),
        ("whey_isolate", 1, "piece"),
        ("lime_zest", 0.5, "tsp"),
    ], None),
    ("pr1-rhubarb-fool", "Rhubarb Whip", "protein", 1, 5, [
        ("milk_2", 0.5, "cup"),
        ("rhubarb", 0.5, "cup"),
        ("strawberry_frozen", 0.5, "cup"),
        ("whey_strawberry", 1, "piece"),
        ("honey", 1, "tbsp"),
    ], "Chop the rhubarb small and cold; long stalks wind around the blade instead of breaking down."),
    ("pr1-black-mission-cream", "Black Mission Cream", "protein", 1, 4, [
        ("milk_whole", 0.5, "cup"),
        ("labneh", 0.25, "cup"),
        ("fig", 2, "piece"),
        ("whey_unflavored", 1, "piece"),
        ("honey", 1, "tsp"),
        ("orange_blossom", 0.5, "tsp"),
    ], "Orange blossom water is potent — half a teaspoon perfumes the whole cup, a full one soaps it."),
    ("pr1-cucumber-doogh", "Doogh Recovery", "protein", 1, 4, [
        ("kefir", 0.75, "cup"),
        ("cucumber", 0.5, "piece"),
        ("ice", 0.5, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("mint", 1, "tbsp"),
        ("salt", 0.25, "tsp"),
    ], "Doogh is salted, not sweet — if it tastes odd, it needs more salt rather than less."),
    ("pr1-bastani-shake", "Bastani Shake", "protein", 1, 3, [
        ("milk_2", 0.5, "cup"),
        ("quark", 0.5, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("pistachio_butter", 1, "tbsp"),
        ("rose_water", 0.5, "tsp"),
        ("honey", 1, "tsp"),
    ], "Rose and pistachio need each other; rose on its own tastes like hand cream."),
    ("pr1-bloody-build", "Bloody Build", "protein", 1, 3, [
        ("tomato_juice", 0.75, "cup"),
        ("cottage_cheese", 0.25, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("lemon_juice", 1, "tbsp"),
        ("hot_sauce", 1, "tsp"),
        ("black_pepper", 0.25, "tsp"),
    ], "Unflavored whey is the only powder that survives a savoury build — vanilla would ruin it."),
    ("pr1-buttermilk-field", "Buttermilk Field", "protein", 1, 4, [
        ("buttermilk", 0.75, "cup"),
        ("cottage_cheese", 0.5, "cup"),
        ("spinach", 1, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("lemon_juice", 1, "tbsp"),
        ("black_pepper", 0.25, "tsp"),
    ], "Buttermilk already carries acid, so go easy on the lemon or the greens turn bitter."),
    ("pr1-mid-august", "Mid-August", "protein", 1, 3, [
        ("watermelon_juice", 0.75, "cup"),
        ("ice", 0.75, "cup"),
        ("whey_isolate", 1, "piece"),
        ("lime_juice", 1, "tbsp"),
        ("mint", 1, "tbsp"),
        ("salt", 0.25, "tsp"),
    ], "Salted watermelon is a summer trick, not a mistake — the pinch makes it taste sweeter."),
    ("pr1-late-bramble", "Late Bramble", "protein", 1, 3, [
        ("buttermilk", 0.75, "cup"),
        ("blackberry_frozen", 0.5, "cup"),
        ("whey_isolate", 1, "piece"),
        ("honey", 1, "tsp"),
        ("lemon_zest", 0.5, "tsp"),
    ], "Buttermilk is thinner than yogurt but twice as tangy — it suits blackberry better."),
    ("pr1-guayaba-crema", "Guayaba Crema", "protein", 1, 3, [
        ("guava_nectar", 0.5, "cup"),
        ("milk_skim", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("cream_cheese", 1, "tbsp"),
        ("whey_vanilla", 1, "piece"),
    ], "Guava and cream cheese is the pastry pairing from every Cuban bakery, cold and drinkable."),

    # ------------------------------------------------ mass-gainer builds
    ("pr1-long-winter", "Long Winter", "protein", 1, 4, [
        ("milk_whole", 1, "cup"),
        ("banana_frozen", 0.5, "cup"),
        ("whey_chocolate", 2, "piece"),
        ("oats", 0.5, "cup"),
        ("peanut_butter", 2, "tbsp"),
    ], "Two scoops is a lot of powder for one cup — add the milk first or it packs under the blade."),
    ("pr1-double-scoop-morning", "Double Scoop Morning", "protein", 1, 4, [
        ("milk_whole", 0.75, "cup"),
        ("whey_vanilla", 2, "piece"),
        ("oats", 0.5, "cup"),
        ("almond_butter", 2, "tbsp"),
        ("date", 2, "piece"),
        ("cinnamon", 0.5, "tsp"),
    ], "If it is too thick to pour, top with milk and pulse twice rather than blending longer."),
    ("pr1-concrete-mixer", "Concrete Mixer", "protein", 1, 3, [
        ("milk_whole", 0.75, "cup"),
        ("casein", 1, "piece"),
        ("whey_chocolate", 1, "piece"),
        ("oats", 0.25, "cup"),
        ("choc_hazelnut", 1, "tbsp"),
    ], "Casein and whey together give you a shake that is thick now and still filling in two hours."),
    ("pr1-offseason-vanilla", "Offseason Vanilla", "protein", 1, 4, [
        ("milk_whole", 0.25, "cup"),
        ("greek_yogurt_whole", 0.5, "cup"),
        ("banana_frozen", 0.5, "cup"),
        ("whey_vanilla", 1, "piece"),
        ("granola", 0.25, "cup"),
        ("honey", 1, "tbsp"),
    ], "Granola goes in last and gets two pulses, so you keep some grit instead of sweet sludge."),
    ("pr1-golden-hour-cashew", "Golden Hour Cashew", "protein", 1, 4, [
        ("milk_whole", 0.75, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("oats", 0.25, "cup"),
        ("cashew_butter", 2, "tbsp"),
        ("date", 2, "piece"),
        ("salt", 0.25, "tsp"),
    ], "Cashew butter is sweeter and softer than almond — it blends in without leaving flecks."),

    # ------------------------------------------------ the rest of the dairy case
    ("pr1-ricotta-cloud", "Ricotta Cloud", "protein", 1, 3, [
        ("milk_skim", 0.5, "cup"),
        ("ricotta", 0.5, "cup"),
        ("ice", 0.5, "cup"),
        ("whey_unflavored", 1, "piece"),
        ("orange_zest", 0.5, "tsp"),
        ("honey", 1, "tbsp"),
    ], "Whole-milk ricotta blends creamy where part-skim stays grainy no matter how long you run it."),
    ("pr1-winter-nog", "Winter Nog", "protein", 1, 3, [
        ("milk_2", 0.75, "cup"),
        ("egg_white", 0.5, "cup"),
        ("casein", 1, "piece"),
        ("maple_syrup", 1, "tbsp"),
        ("nutmeg", 0.25, "tsp"),
        ("vanilla_extract", 0.5, "tsp"),
    ], "Pasteurized whites whip up airy in the Blast, which is what makes this taste like nog."),
]
